# Rocprof metric obtained via --stats

[LDSBankConflict]
label = "LDS Bank Conflict"
unit = "%"

[LDSInsts]
label = "LDS instructions"
unit = ""
break=1

## Rocprof derived metric
#[FETCH_SIZE]
#label = "HBM Read"
#unit = "KiB"
#
## Rocprof derived metric
#[WRITE_SIZE]
#label = "HBM Write"
#unit = "KiB"
#
#[HBM]
#label = "HBM"
#unit = "KiB"
#operation = "(FETCH_SIZE + WRITE_SIZE)"
#
#[HBMBandwidth]
#label = "HBM Bandwidth"
#unit = "KiB/ns"
#operation = "(FETCH_SIZE + WRITE_SIZE) / DurationNs"
#break=1
