# This metric file uses a few rocprof counters that can be collected in a single pass.
# The collected counters show the amount of data moved as reads and writes over HBM.

# Rocprof metric obtained via --stats
[DurationNs]
label = "Duration"
unit = "ns"
break = 1

# Rocprof derived metric
[FETCH_SIZE]
label = "HBM Read"
unit = "KiB"

# Rocprof derived metric
[WRITE_SIZE]
label = "HBM Write"
unit = "KiB"

[TCP_TOTAL_CACHE_ACCESSES_sum]
label = "L1 count"
unit = "B"
hide = 1

[TCP_TCC_READ_REQ_sum]
label = "L2 read count"
unit = "B"
hide = 1

[TCP_TCC_WRITE_REQ_sum]
label = "L2 write count"
unit = "B"
hide = 1

[HBM]
label = "HBM"
unit = "KiB"
operation = "(FETCH_SIZE + WRITE_SIZE)"

[L1]
label = "L1"
unit = "B"
operation = "TCP_TOTAL_CACHE_ACCESSES_sum * 64"

[L2Read]
label = "L2 Read"
unit = "B"
operation = "TCP_TCC_READ_REQ_sum * 64"

[L2Write]
label = "L2 Write"
unit = "B"
operation = "TCP_TCC_WRITE_REQ_sum * 64"
break=1

[HBMReadBandwidth]
label = "HBM Read Bandwidth"
unit = "KiB/ns"
operation = "FETCH_SIZE / DurationNs"

[HBMWriteBandwidth]
label = "HBM Write Bandwidth"
unit = "KiB/ns"
operation = "WRITE_SIZE / DurationNs"

[HBMBandwidth]
label = "HBM Bandwidth"
unit = "KiB/ns"
operation = "(FETCH_SIZE + WRITE_SIZE) / DurationNs"

[L1Bandwidth]
label = "L1 Bandwidth"
unit = "B/ns"
operation = "(TCP_TOTAL_CACHE_ACCESSES_sum * 64) / DurationNs"

[L2ReadBandwidth]
label = "L2 Read Bandwidth"
unit = "B/ns"
operation = "(TCP_TCC_READ_REQ_sum * 64) / DurationNs"

[L2WriteBandwidth]
label = "L2 Write Bandwidth"
unit = "B/ns"
operation = "(TCP_TCC_WRITE_REQ_sum * 64) / DurationNs"
break=1


